.changeset/tame-gifts-rush.md
apps/storybook/.storybook/preview.js
apps/storybook/src/Background.stories.tsx
apps/storybook/src/BackgroundStack.tsx
apps/storybook/src/Box.stories.tsx
apps/storybook/src/Grid.stories.tsx
apps/storybook/src/Heading.stories.tsx
apps/storybook/src/Icon.stories.tsx
apps/storybook/src/Iconography.stories.tsx
apps/storybook/src/Spacer.stories.tsx
apps/storybook/src/Stack.stories.tsx
apps/storybook/src/Text.stories.tsx
apps/storybook/src/TextField.stories.tsx
apps/storybook/src/Typography.stories.tsx
package.json
packages/web-ui/src/Background/Background.tsx
packages/web-ui/src/Background/index.ts
packages/web-ui/src/Box/Box.tsx
packages/web-ui/src/Grid/Grid.tsx
packages/web-ui/src/Spacer/Spacer.tsx
packages/web-ui/src/Stack/Stack.tsx
packages/web-ui/src/index.ts

- https://linear.app/utilitywarehouse/issue/UWDS-141/deprecate-and-remove-background-component
- https://linear.app/utilitywarehouse/issue/UWDS-210/support-system-props-on-box-and-layout-components

Support system props on Box & layout components 

---

packages/web-ui/.storybook/main.js
packages/web-ui/package.json
pnpm-lock.yaml

[Ticket](https://linear.app/utilitywarehouse/issue/UWDS-77/add-a11y-add-ons-to-web-ui)

Add a11y add-ons to Web UI

---

.changeset/young-wolves-double.md
packages/web-ui/package.json
pnpm-lock.yaml

Reverts utilitywarehouse/design-systems#113

Revert "pin react spectrum packages"

---

.changeset/green-ladybugs-cross.md
packages/web-ui/src/HelperText/HelperText.tsx

Updates helper text colours making icon and text the same colour.

chore: update helper text colours

---

packages/web-ui/docs/colour-system/common.mdx
packages/web-ui/docs/components/ColourDisplay.tsx

I got bored at home 😁 
- added hex value to color docs
- tidied them to look nicer 💅🏻 
- brought the common colors docs inline with the others

Update colour system docs

---

apps/native-ui-storybook/components/Box/Docs.mdx
apps/native-ui-storybook/package.json
package.json
patches/@react-native-community+datetimepicker+7.6.2.patch
pnpm-lock.yaml

Temporarily fixes build issues for Native UI Storybook since updating to Xcode 15.3 see:
https://github.com/react-native-datetimepicker/datetimepicker/issues/866

chore: temp patch for xcode 15.3

---

apps/native-ui-storybook/.storybook/preview.tsx
apps/native-ui-storybook/docs/components/BackToTopButton.tsx
apps/native-ui-storybook/docs/native-ui/guides/styling.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/color-mode.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/components/GSExample.tsx
apps/native-ui-storybook/docs/native-ui/guides/styling/components/RNExample.tsx
apps/native-ui-storybook/docs/native-ui/guides/styling/descendants.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/overview.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/platform-specific.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/responsive.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/state.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/utility-props.mdx

This pull request adds documentation for styling in the Native UI project. It includes an overview of the styling engine, color mode, platform-specific styles, and descendant styling. It also includes examples and code snippets for each topic.

chore: add styling documentation

---

apps/native-ui-storybook/.storybook/preview.tsx
apps/native-ui-storybook/App.tsx
apps/native-ui-storybook/assets/style.css
apps/native-ui-storybook/docs/native-ui/guides/styling/descendants.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/fonts.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/utility-props.mdx
apps/native-ui-storybook/docs/native-ui/introduction.mdx
packages/native-ui/src/components/custom/Alert/AlertLink/styled-components/Text.tsx
packages/native-ui/src/components/custom/Alert/AlertTitle/styled-components/Root.tsx
packages/native-ui/src/config/gluestack-ui.config.ts
packages/native-ui/src/config/theme/Badge.ts
packages/native-ui/src/config/theme/BadgeText.ts
packages/native-ui/src/utils/mapFontWeights.ts
packages/native-ui/src/utils/mapFonts.ts

This pull request updates the font styles and mappings in the codebase as well as documentation. It includes the following commits:
- feat: font map
- chore: add font docs
The changes in this pull request include updating the font families and font weights in various components. It also includes adding a utility function to map font weights. Additionally, the pull request updates the font files used in the project.

feat: add font styles and mappings

---

.github/workflows/previews-cleanup.yml
apps/native-ui-storybook/.storybook/preview.tsx
apps/native-ui-storybook/docs/native-ui/guides/hooks.mdx
apps/native-ui-storybook/docs/native-ui/guides/tokens.mdx

This pull request adds documentation for design tokens and the useToken, useBreakpointValue, useMedia, useColorMode, and useStyled hooks in the Native UI library. The documentation includes examples and explanations for each hook, demonstrating how they can be used in React Native applications.

chore: add tokens and hooks documentation

---

.changeset/silly-doors-rule.md
packages/web-ui/src/BaseButton/BaseButton.props.ts
packages/web-ui/src/lab/Button/Button.stories.tsx

Update lab/Button types to guard against dead prop combinations.

---

.eslintrc.js
packages/web-ui/src/utils/with-breakpoints.ts

https://tkdodo.eu/blog/array-types-in-type-script

prefer generic arrays

---

.changeset/sharp-socks-agree.md
packages/web-ui/src/UnstyledButton/UnstyledButton.props.ts
packages/web-ui/src/lab/Link/Link.props.ts

https://twitter.com/JonasBadalic/status/1765006152150974919

Prefer interfaces

---

.github/workflows/generate-colour-system.yml

- add generate action
- update generate action

update generate workflow

---

packages/colour-system/GENERATION.md

- update generate action
- add generate docs

add generate docs

---

.changeset/selfish-pandas-love.md
.changeset/tasty-taxis-ring.md
packages/codemod/package.json
pnpm-lock.yaml

- clean out & restart
- rip & replace codemod cli
- deps

codemod dev

---

.changeset/curly-penguins-grow.md
.changeset/selfish-pandas-love.md
.changeset/tasty-taxis-ring.md
.changeset/thin-adults-yell.md
packages/codemod/bin/codemod.js

- rip & replace codemod cli
- deps
- delete changeset
- add changeset
- fix

codemod dev 2

---

.changeset/curly-penguins-grow.md
.changeset/new-lions-tickle.md
.changeset/selfish-pandas-love.md
.changeset/tasty-taxis-ring.md
.changeset/thin-adults-yell.md
packages/codemod/bin/codemod.js

- rip & replace codemod cli
- deps
- delete changeset
- add changeset
- fix
- fix

codemod dev 3

---

.changeset/six-wolves-film.md
packages/codemod/transforms/web-ui/v0/__testfixtures__/import-paths.input.tsx
packages/codemod/transforms/web-ui/v0/__testfixtures__/import-paths.output.tsx
packages/codemod/transforms/web-ui/v0/import-paths.js

- update codemod package
- update codemod package

rphoenix uwds 2368

---

.changeset/chatty-jeans-explode.md
packages/codemod/package.json
packages/codemod/transforms/web-ui/v0/__testfixtures__/typography-to-heading-and-text.input.tsx
packages/codemod/transforms/web-ui/v0/__testfixtures__/typography-to-heading-and-text.output.tsx
packages/codemod/transforms/web-ui/v0/__tests__/typography-to-heading-and-text.test.js
packages/codemod/transforms/web-ui/v0/background-to-box.js
packages/codemod/transforms/web-ui/v0/optional.js
packages/codemod/transforms/web-ui/v0/typography-to-heading-and-text.js
packages/web-ui/docs/web-ui/guides/migration/v0.mdx
packages/web-ui/src/Typography/Typography.stories.tsx

- add Typography codemod
- update codemod to deal with props

Add `Typography` component codemod

---

.changeset/nervous-hats-fly.md
packages/codemod/transforms/web-ui/v0/background-to-box.js
packages/codemod/transforms/web-ui/v0/typography-to-heading-and-text.js

codemod fix

---

.changeset/tidy-masks-refuse.md
packages/native-ui/src/config/gluestack-ui.config.ts

Removes broken font resolver which caused text styling to break

fix: remove broken font resolver

---

apps/native-ui-storybook/components/lab/Actionsheet/Actionsheet.docs.mdx
apps/native-ui-storybook/docs/components/VariantTitle.tsx
apps/native-ui-storybook/docs/native-ui/guides/contributing.mdx
apps/native-ui-storybook/docs/native-ui/guides/migration.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/color-mode.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/descendants.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/fonts.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/platform-specific.mdx
apps/native-ui-storybook/docs/native-ui/guides/styling/responsive.mdx
apps/native-ui-storybook/docs/native-ui/guides/tokens.mdx
apps/native-ui-storybook/docs/native-ui/introduction.mdx
packages/native-ui/src/config/gluestack-ui.config.ts

This pull request includes updates to the documentation and the addition of migration docs.

chore: add `uw-native-ui` migration docs

---

.github/workflows/previews-cleanup.yml
.github/workflows/previews.yml
apps/native-ui-storybook/docs/native-ui/guides/migration.mdx

chore: update migration docs

---

README.md

note: catch up with @jordmccord before merging 👍🏻

add branch docs

---

.changeset/popular-queens-exercise.md
packages/web-ui/docs/web-ui/introduction.mdx
packages/web-ui/src/Menu/Menu.docs.mdx
packages/web-ui/src/Menu/Menu.stories.tsx
packages/web-ui/src/Stack/Stack.docs.mdx
packages/web-ui/src/Stack/Stack.stories.tsx
packages/web-ui/src/TextField/TextField.docs.mdx
packages/web-ui/src/TextField/TextField.stories.tsx
packages/web-ui/src/TextField/TextField.tsx
packages/web-ui/src/ToggleButton/ToggleButton.docs.mdx
packages/web-ui/src/ToggleButton/ToggleButton.tsx
packages/web-ui/src/ToggleButton/ToggleButtonGroup.stories.tsx

- Update ToggleButton without ThemeProvider
- update Menu docs
- update TextField without ThemeProvider
- update Stack docs
- update docs
- update changeset

Update `ThemeProvider` usage & docs

---

.changeset/kind-donuts-brush.md
packages/native-ui/src/config/theme/Icon.ts

Fixs this issue https://utilitywarehouse.slack.com/archives/C04MKBQ34PJ/p1722434717668299

fix: set default icons stroke width to 0

---

.github/workflows/checks.yml
package.json
pnpm-lock.yaml
turbo.json

- Upgrades turborepo to v2
- Only runs jobs with changes affected in the current branch

chore: upgrade to turborepo v2

---

.changeset/fast-plants-talk.md
.changeset/tough-worms-laugh.md
packages/codemod/transforms/web-ui/v1/__testfixtures__/migrate-button-v0.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/migrate-button-v0.output.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/migration-v0.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/migration-v0.output.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/rename-icon-button-size-v0.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/rename-icon-button-size-v0.output.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/rename-lab-button-size-v0.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/rename-lab-button-size-v0.output.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/rename-legacy-imports.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/rename-legacy-imports.output.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/typography-to-heading-and-text-v0.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/typography-to-heading-and-text-v0.output.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/update-v0-lab-imports.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/update-v0-lab-imports.output.tsx
packages/codemod/transforms/web-ui/v1/__tests__/migrate-button.test.js
packages/codemod/transforms/web-ui/v1/__tests__/migration.test.js
packages/codemod/transforms/web-ui/v1/__tests__/rename-icon-button-size.test.js
packages/codemod/transforms/web-ui/v1/__tests__/rename-lab-button-size.test.js
packages/codemod/transforms/web-ui/v1/__tests__/rename-legacy-imports.test.js
packages/codemod/transforms/web-ui/v1/__tests__/typography-to-heading-and-text.test.js
packages/codemod/transforms/web-ui/v1/__tests__/update-lab-imports.test.js
packages/codemod/transforms/web-ui/v1/migrate-button.js
packages/codemod/transforms/web-ui/v1/rename-icon-button-size.js
packages/codemod/transforms/web-ui/v1/rename-lab-button-size.js
packages/codemod/transforms/web-ui/v1/rename-legacy-imports.js
packages/codemod/transforms/web-ui/v1/typography-to-heading-and-text.js
packages/codemod/transforms/web-ui/v1/update-lab-imports.js
packages/web-ui/docs/web-ui/guides/migration/v1.mdx

- handle web-ui-v0 imports
- add codemod to rename legacy imports

Codemods to support partial migration

---

.changeset/sour-pandas-move.md
packages/codemod/transforms/web-ui/v1/__testfixtures__/migrate-button-href-customer-ui-material.input.tsx
packages/codemod/transforms/web-ui/v1/__testfixtures__/migrate-button-href-customer-ui-material.output.tsx
packages/codemod/transforms/web-ui/v1/__tests__/migrate-button.test.js
packages/codemod/transforms/web-ui/v1/migrate-button.js

Fix codemod

---

apps/native-ui-storybook/components/Button/components/ButtonVariants.tsx
apps/native-ui-storybook/components/IconButton/IconButton.docs.mdx
apps/native-ui-storybook/components/IconButton/IconButton.tsx
apps/native-ui-storybook/components/IconButton/PlaygroundVariants.tsx
apps/native-ui-storybook/components/IconButton/components/IconButtonVariants.tsx
packages/native-ui/src/components/IconButton/IconButton.context.ts
packages/native-ui/src/components/IconButton/IconButton.props.ts
packages/native-ui/src/components/IconButton/IconButton.tsx
packages/native-ui/src/components/IconButton/IconButtonIcon.tsx
packages/native-ui/src/components/IconButton/IconButtonRoot.tsx
packages/native-ui/src/components/IconButton/IconButtonSpinner.tsx
packages/native-ui/src/components/IconButton/config.json
packages/native-ui/src/components/IconButton/index.tsx
packages/native-ui/src/components/IconButton/styled-components/Icon.tsx
packages/native-ui/src/components/IconButton/styled-components/Root.tsx
packages/native-ui/src/components/IconButton/styled-components/index.tsx

refactor: `IconButton` styles library

---

.changeset/cuddly-pandas-check.md
.changeset/flat-mice-exist.md
.changeset/four-rings-jam.md
.changeset/funny-ears-attack.md
.changeset/giant-bags-grab.md
.changeset/good-scissors-tell.md
.changeset/rare-hornets-cry.md
.changeset/rude-sloths-mate.md
.changeset/soft-books-guess.md
.changeset/stale-ducks-complain.md
.changeset/tall-eyes-add.md
.changeset/two-donuts-drum.md

chore: add `native-ui` changesets

---

.changeset/few-wasps-teach.md
packages/native-ui/src/components/Text/Text.props.ts
packages/native-ui/src/components/Text/Text.tsx

feat: add text decoration utility style props to `Text` component

---

.changeset/violet-chairs-eat.md
apps/native-ui-storybook/components/Box/Box.stories.tsx
apps/native-ui-storybook/components/Box/Box.tsx
apps/native-ui-storybook/components/lab/Box/Box.docs.mdx
apps/native-ui-storybook/components/lab/Box/Box.stories.tsx
apps/native-ui-storybook/components/lab/Box/Box.tsx
apps/native-ui-storybook/components/lab/Box/BoxWithRef.tsx
packages/native-ui/src/lab/Box/Box.props.ts
packages/native-ui/src/lab/Box/Box.tsx

feat: add `as` prop to lab `Box`

---

.changeset/wild-hairs-behave.md
packages/colour-system/.gitignore
packages/web-ui/package.json
pnpm-lock.yaml

- fix mui deps
- add changeset

fix `@mui` deps

---

packages/web-ui/src/components/CheckboxGroup/CheckboxGroup.figma.tsx
packages/web-ui/src/components/CheckboxTile/CheckboxTile.figma.tsx

fix checkbox code connect

---

apps/native-ui-storybook/.storybook/main.ts
apps/native-ui-storybook/docs/native-ui/introduction.mdx
apps/native-ui-storybook/package.json
apps/native-ui-storybook/scripts/postinstall.js
packages/native-ui/src/components/Spinner/Spinner.tsx
packages/native-ui/src/components/Spinner/Spinner.web.tsx
pnpm-lock.yaml

chore(native-ui): add a11y storybook addon

---

.changeset/weak-comics-guess.md
packages/native-ui/src/components/Button/ButtonRoot.tsx

fix(native-ui): small `Button` horizontal padding

---

.changeset/giant-moles-trade.md
apps/native-ui-storybook/components/Button/Variants.tsx
apps/native-ui-storybook/components/Button/components/ButtonVariants.tsx
apps/native-ui-storybook/components/IconButton/Variants.tsx
apps/native-ui-storybook/docs/native-ui/guides/hooks.mdx
packages/native-ui/src/core/breakpoints.ts
packages/native-ui/src/core/themes.ts
packages/native-ui/src/hooks/index.ts
packages/native-ui/src/hooks/useBreakpointValue.ts
packages/native-ui/src/hooks/useColorMode.ts
packages/native-ui/src/hooks/useMedia.ts
packages/native-ui/src/hooks/useTheme.ts
packages/native-ui/src/hooks/useToken.ts

refactor(native-ui): hooks away from gluestack

---

packages/web-ui/src/components/Alert/Alert.docs.mdx
packages/web-ui/src/storybook-components/BackToTop.tsx
packages/web-ui/src/storybook-components/DocsHeader.tsx
packages/web-ui/src/storybook-components/index.ts

add BackToTop button

---

packages/figma-variables-plugin/package.json
packages/figma-variables-plugin/src/app/components/App.tsx
packages/figma-variables-plugin/webpack.config.js
pnpm-lock.yaml

See [docs](https://uw-web-ui.vercel.app/iframe.html?viewMode=docs&id=web-ui-introduction--documentation#es-modules)

Fix Figma plugin build

---

apps/native-ui-storybook/components/TimedRender.tsx
apps/native-ui-storybook/components/lab/Box/Box.stories.tsx
apps/native-ui-storybook/components/lab/Box/BoxPerfTest.tsx
packages/native-ui/src/lab/index.ts

chore: add perf test component and test Box

---

.changeset/shiny-pigs-battle.md
apps/native-ui-storybook/.storybook/preview.tsx
apps/native-ui-storybook/components/ToggleButton/ToggleButton.docs.mdx
apps/native-ui-storybook/components/ToggleButton/ToggleButton.stories.tsx
apps/native-ui-storybook/docs/components/AllComponents.web.tsx
packages/native-ui/src/components/ToggleButton/ToggleButton.context.ts
packages/native-ui/src/components/ToggleButton/ToggleButton.props.ts
packages/native-ui/src/components/ToggleButton/ToggleButton.tsx
packages/native-ui/src/components/ToggleButton/ToggleButtonGroup.context.ts
packages/native-ui/src/components/ToggleButton/ToggleButtonGroup.props.ts
packages/native-ui/src/components/ToggleButton/ToggleButtonGroup.tsx
packages/native-ui/src/components/ToggleButton/ToggleButtonIcon.tsx
packages/native-ui/src/components/ToggleButton/ToggleButtonRoot.tsx
packages/native-ui/src/components/ToggleButton/ToggleButtonText.tsx
packages/native-ui/src/components/ToggleButton/index.ts
packages/native-ui/src/components/index.ts

feat(native-ui): `ToggleButton` component

---

.changeset/little-turtles-shake.md
packages/native-ui/src/hooks/useLightDark.ts

fix: light dark hook theme check

---

apps/native-ui-storybook/.gitignore
apps/native-ui-storybook/docs/native-ui/guides/migration.mdx
packages/native-ui/.gitignore

chore: update `uw-native-ui` migration docs

---

packages/web-ui/docs/colour-system/migration.mdx

- update colour system migration docs
- update colour system migration docs

colours docs

---

.changeset/six-books-smoke.md
packages/codemod/transforms/web-ui/v0/import-paths.js

Remove console.log
